### ISSUE TITLE
NAC website text / format changes

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1013]
Presumably the low-hanging fruit for the UI/UX enhancements of #890.

**update with contents of #914**

**Query form (root page):**
- [ ] Remove “NAC Query Tool” heading
- [ ] Change "Search for SNAP Participants" to an h2 element (and do the same on the query results page)
- [ ] Add " (optional)" to Middle name field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Add "(xxx-xx-xxxx)" to SSN field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Change "Submit" on the form to "Search" (and do the same on the query results page)
- [ ] Change order of name fields to First, Middle, Last (and do the same on the query results page). Main goal is to sync format / order with query and lookup ID results, open to taking the lowest-effort path.
- [ ] Place date of birth field above SSN to match the query results table
- [ ] Change page title from “NAC Query Tool - Piipan.QueryTool” to ”NAC Participant Search”

**Query results page:**
- [ ] Remove “NAC Query Results” heading
- [ ] Change "Benefits End" heading to "Benefits end"

**~~Lookup by ID page (/LookupById):~~**
- ~~Remove "NAC Query Tool" heading~~
- ~~Make "Search by Lookup ID" an h2 element (should also apply to the search results page)~~
- ~~Change "Submit" button to "Search" (should also apply to the search results page)~~
- ~~Add " (7 digits)" to the Lookup ID field label (should also apply to the search results page)~~
  - ~~bonus: make “(7 digits)” slightly lighter, e.g.  #757575 (USWDS gray-50)~~
- ~~Change page title from “NAC Query Tool - Piipan.QueryTool” to ”NAC Participant Lookup”~~

**Comment by juliaklindpaintner** [comment]
@cjhskippy Here are my proposed initial updates to this — stripped out everything related to Lookup ID.

**Query form (root page):**
- [ ] Remove “NAC Query Tool” heading
- [ ] Change "Search for SNAP Participants" to an h2 element (and do the same on the query results page)
- [ ] Add " (optional)" to Middle name field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Add "(xxx-xx-xxxx)" to SSN field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Change "Submit" on the form to "Search" (and do the same on the query results page)
- [ ] Change order of name fields to First, Middle, Last (and do the same on the query results page). Main goal is to sync format / order with query and lookup ID results, open to taking the lowest-effort path.
- [ ] Place date of birth field above SSN to match the query results table
- [ ] Change page title from “NAC Query Tool - Piipan.QueryTool” to ”NAC Participant Search”

**Query results page:**
- [ ] Remove “NAC Query Results” heading
- [ ] Change "Benefits End" heading to "Benefits end"

**Comment by echappen** [comment]
> Change "Benefits End" heading to "Benefits end"

@juliaklindpaintner Current table header is "Benefits end month." Did you want it to just say "Benefits end"? 

<img width="174" alt="Screen Shot 2021-08-12 at 10 48 22 AM" src="https://user-images.githubusercontent.com/4267629/129227793-b1161465-46c8-49d5-b897-0babc57ff31c.png">

**Comment by juliaklindpaintner** [comment]
@echappen No need to change! I think it used to be Benefits end — but the point was the capitalization, not the words.
