### ISSUE TITLE
Use deidentified PII in query API

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1215]
As a state agency developer, I want to be able to query for participants using the deidentified hash instead of submitting PII directly so that I can protect the privacy of SNAP participants in my state.

AC:
Query API...
- [ ] ~~No longer allows states to provide name, DOB, SSN~~
- [ ] Allows internal methods to continue to query by name, DOB, SSN (does not need to work for the purposes of this story) (see #1540)
- [x] Accepts deidentified hash
- [x] Requires hash to be formatted properly
- [x] Has updated documentation (see #1452)
- [ ] Includes updated test data sets for users to query against and verify successful use (see #1213 )
