### ISSUE TITLE
Updated roadmap with detailed scope

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1694]
To accompany the schedule outlining our path to an MVP release, provide details of the capabilities provided at each milestone that FNS can review.

- [x] Document scope of features included in MVP plan and share with FNS
- [x] Update roadmap to provide better understanding of launch strategy
- [x] Clear initial scope + roadmap with FNS

**Comment by cjhskippy** [comment]
Noting that some follow-on decisions are outstanding in #2314, but the initial scope and roadmap was sufficient to share, so considering this closed.
