### ISSUE TITLE
Epic: Discover duplicate participation

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#23]
_from mural card: Simple + easy process to discover duplicate participation_

As a state user, I want to know about duplicate participants so that I can take action to prevent enrolling a person twice or take appropriate action when someone is already participating twice.
- [ ] Process is simple
- [ ] Adheres to statutory requirements
- [ ] Protects PII
- [ ] Online as much as is needed
