### ISSUE TITLE
Act on a preventative NAC match

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#258]
As a State agency eligibility worker, I need to be able to follow up with another state agency in response to a NAC match that I find while screening an application, recertification, or addition of a household member to an existing case.

- [ ] Verify name, DOB, SSN used in NAC match is correct
- [ ] Divide household into groups relevant to each out of state inquiry
- [ ] Get contact info for the out of state inquiry
- [ ] Have a unique identifier that I can give to the other SA worker to access PII
- [ ] Send an out-of-state-inquiry (assume will be via email for this iteration)
- [ ] Receive notification when results of out-of-state-inquiry are available
- [ ] Read results of out-of-state inquiry
- [ ] Have some visible indicator when match is resolved so I know the case can be processed.

As a state agency eligibility worker receiving an out-of-state inquiry, I want to be able to address NAC matches reported by other states so that participants who are eligible for benefits in my state continue to receive them and participants who have moved can have their cases closed + reopened in their new state of residence.

- [ ] Receive notification: there is a match I need to act on
- [ ] Access PII using a unique match code
- [x] Verify this person is receiving benefits in my state (will happen outside of Piipan)
- [ ] Provide notice to participants and modify case(s) as appropriate (will happen outside of Piipan)
- [ ] Send response to initiating state
