### ISSUE TITLE
Allow states to upload lists of current enrollees

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#41]
As the person maintaining a state SNAP processing system, I want to be able to upload current rosters of SNAP enrollees in my state so that our eligibility workers get accurate reports of possible duplicate enrollment by other states.

This process will happen at least daily, and will include the information of each household member who is receiving SNAP benefits in the state.

- [ ] API will accept bulk uploads of current enrollees
  - [ ] #8 - Webservice accepts a small, correctly-formatted CSV
    - [ ] ~~Each bulk upload for a state replaces prior enrollment data for that state~~ (covered in #8)
  - [ ] #64 (Milestone 5) - Production-ready bulk upload API
- [ ] #85 - User research for data sharing
- Research needed: will states require bulk uploads that aren't API-driven?  _Example: use MoveIT or similar tool to drop files in a place that is regularly scanned by a batch process_

**Comment by cjhskippy** [comment]
This issue has outlived its usefulness as a collection of related issues - the content of epic #64 captures any remaining useful tasks.
