### ISSUE TITLE
Bulk upload rejects unusable data

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#43]
As a NAC business owner, I want the NAC to reject data uploads that are unusable so the system doesn't provide inaccurate results or otherwise behave oddly

- [x] If the entire bulk upload is formatted incorrectly, it is rejected
  - [x] return 400 (bad request) response code
- [ ] Individual rows that fail to meet acceptable criteria are rejected
  - [ ] ~~Sanitize inputs against injection attacks~~ (#448)
  - [x] If any of the required fields are not provided, the row is rejected.  This includes rows that are missing any one of these:
    - [ ] ~~First name~~ (moved to issue #445)
    - [x] last name
    - [x] date of birth
    - [x] ssn
  - [x] If optional fields are left out, the row is accepted.  Rows missing only these fields should still be allowed:
    - [x] middle name
  - [x] SSN is verified as a nine-digit positive integer
  - [ ] ~~date of birth is a valid date on or after 1/1/1900 up to the current date~~ (#448)
  - [ ] ~~All valid rows in the bulk upload are successfully processed even if some other rows are rejected~~ (#446)
  - [ ] ~~For each row that is rejected, provide the client with~~ (#446)
    - [ ] ~~the row number that was rejected~~
    - [ ] ~~a reason why the row could not be processed~~

**Comment by cjhskippy** [comment]
Remaining pieces of this issue have been divided into other stories, some of which are MVP, others less urgent.  Can close this one.
