### ISSUE TITLE
Provide high confidence that matches are accurate

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#46]
As a state eligibility worker, I want to be confident that reported matches are accurate so that I don't waste time investigating false positives or allow duplicate enrollment to take place.

- [ ] #29 - Capable of supporting other high-accuracy match methods
- [ ] Avoid false positives
- [ ] Avoid missed matches
  - [ ] Handle name variations stemming from names with: multiple first names, multiple last names, middle names, suffixes. (also typos?)
- [ ] Mechanism to evaluate accuracy of reported matches, learn, and improve
