### ISSUE TITLE
Accept case number and participant ID during bulk uploads

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#597]
This story combines two user stories:

As a State agency worker in a matching state, I want to know the relevant case number so that I can quickly find the correct participant record and efficiently handle matches within the same household.

As a State agency worker in a matching state, I want to quickly look up the correct record for a participant.  The participant's unique identifier may be an even better way to find participants than SSN.  (SSN is not always unique)

In order to allow states to find the right records when a match is discovered, bulk upload should:
- [ ] Require the inclusion of a "case identifier" related to each participant record.
  - [ ] Participant records without a case identifier are rejected
Notes: We can't be certain that this is always a number.  It might be a string of alphanumeric characters.  This  will not be unique within a state - many individuals in the same state may share the same case number.
- [ ] Allow the inclusion of a participant ID for each individual.
  - [ ] Participant records without a participant ID are accepted if all other validations pass
We can expect this identifier to be a unique string for each participant record within a state (two participants at different states may share the same identifier, however).  It may not be necessary for the NAC to enforce uniqueness.
- [ ] Explicitly call out requirement that participant ID must not include SSN in documentation provided to states.

## TODO
- [ ] Add columns to database in iac scripts
- [ ] updated ETL function to accept new columns as input
- [ ] update example csv
- [ ] update Open API documentation; regenerate markdown docs

**Comment by echappen** [comment]
@ryanhofdotgov Should I deal with data migrations here for adding the columns to the database, or drop the databases when running iac? Thinking of just adding the fields [here](https://github.com/18F/piipan/blob/main/ddl/per-state.sql#L29) but I think that would entail a database drop for the change to take place.

**Comment by ryanhofdotgov** [comment]
I think we just punt it a little longer and just consider it "infrastructure" that needs to be manually dropped on our existing instances and then let IaC recreate it. I would not put the database drop in the IaC itself, you could write a short ancillary script to drop them, kind of like the one we have to delete the resource groups.

**Comment by ryanhofdotgov** [comment]
@echappen Would you review and check off all the acceptance criteria above? I'm thinking that last one is not applicable and should be crossed out. Thanks!

**Comment by echappen** [comment]
Done!

**Comment by ryanhofdotgov** [comment]
@echappen Sorry, I was vague – I meant the need to update OpenAPI docs – I don't think that was needing to be done as part of this work, since only the CSV was updated.

**Comment by echappen** [comment]
Got it, thanks for clarifying. (I'm realizing in this process that the CSV import schema is serving sort of serving as API documentation.)
