### ISSUE TITLE
Production-ready bulk data uploads

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#64]
As a state IT professional, I want to be able to share bulk SNAP participant information with the NAC in an automated fashion so that the match records are accurate.

  - [ ] If successful, upload affects only the appropriate state database. Affected state is determined by credentials provided to client app (e.g. don't trust the API user to assign the correct state) (this will require a method to generate credentials for each client app)
  - [ ] #43 - Validate input and reject rows that are not correctly formatted.
  - [ ] API is documented with enough info for states to use it
  - [ ] Log success / failure for the upload, number of records accepted, number rejected
  - [ ] Daily task simulates bulk state uploads
  - [ ] Verify capacity to handle peak upload volume
  - [ ] Additional validation as desired: make sure DOB is believable / SSN is valid / check all 3 against a canonical source
  - [ ] Define what is reasonable for response times given size of files to upload, processing that has to happen on that data, and users' needs.  Should not need to provide near-instant results like the API calls to see if single participants are matches.
  - [ ] Define: what is best behavior when bulk uploads are malformed?
  - [ ] Define: what do we do about duplicates? Will this ever happen?
