### ISSUE TITLE
Production-ready API to prevent individuals from duplicate enrollment

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#70]
Update the basic individual match api from #26 to be fully production ready.

- [ ] #28 - API is only accessible by authorized computer systems
- [ ] #35 - API has good documentation to allow state developers to use it.
- [ ] #37 - Provide API versioning (ability to change API over time without breaking client implementations)
- [ ] #47 - API is elastic (automatically adapts as usage increases + decreases)
- [ ] #51 - API meets uptime + disaster recovery needs (Epic)
- [ ] #39 - Results should be near-real-time, even at anticipated peak usage
- [ ] Validate these inputs to catch mistakes (invalid SSN, unbelievable birthday, compare all against a canonical database, or some other form of verification)
