### ISSUE TITLE
Stream all resource logs to an event hub

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#729]
As a security engineer, I want to integrate all resource logs from the system with a 3rd party Security Information and Event Management (SIEM) tool like Splunk. Azure solution is Azure Monitor with Event Hub.

Some reference docs to start with:
- https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-metrics-azure-monitor
- https://azure.microsoft.com/en-us/updates/new-app-service-integration-with-azure-monitor-preview/
- https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-diagnostic-logs
- https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/tutorial-azure-monitor-stream-logs-to-event-hub

**Comment by ryanhofdotgov** [comment]
From discussion with FastTrack:
* https://www.splunk.com/en_us/blog/tips-and-tricks/splunking-microsoft-azure-monitor-data-part-1-azure-setup.html
* https://www.splunk.com/en_us/blog/tips-and-tricks/splunking-microsoft-azure-monitor-data-part-2-splunk-setup.html

And also:
* https://splunkbase.splunk.com/app/3110/#/overview
* https://docs.splunk.com/Documentation/AddOns/released/MSCloudServices/About
* https://www.splunk.com/en_us/blog/tips-and-tricks/getting-microsoft-azure-data-into-splunk.html
* https://techcommunity.microsoft.com/t5/azure-sentinel/sending-enriched-azure-sentinel-alerts-to-3rd-party-siem-and/ba-p/1456976

**Comment by ryanhofdotgov** [comment]
1st priority is stream Front Door logs to Event Hub.

**Comment by ryanhofdotgov** [comment]
Removing "spike" in subject line, as I think we should be able to move beyond just the research phase in this sprint.

**Comment by kingcomma** [comment]
Adding diagnostic settings (i.e., directing resource logs to event hub) via ARM template: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-manager-diagnostic-settings

Using `az` CLI to discovery available log categories: https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings/categories?view=azure-cli-latest#az_monitor_diagnostic_settings_categories_list

**Comment by kingcomma** [comment]
@ryanhofdotgov With front door logs now set up, is there a priority for the remaining resources? If not, I'll just go through our list type-by-type.

**Comment by ryanhofdotgov** [comment]
@kingcomma I'd do APIM (since it's meant to be externally facing) first, then after that doesn't really matter.

**Comment by kingcomma** [comment]
Resources logs to stream:
- [x] Front Door for Query Tool and Dashboard (#917)
- [x] Per-state match API Functions (#944)
- [x] Orchestrator match API Function (#944)
- [x] APIM (#938)
- [x] Per-state upload storage accounts (#950)
- [ ] Per-state ETL Functions
- [ ] Participant records PostgreSQL Server
- [ ] Core PostgreSQL Server
- [ ] Azure Active Directory (needs research — assumes managed identity usage logging happens here)
- [ ] Query Tool and Dashboard App Service instances
- [ ] Metrics API and Collection Functions

**Comment by kingcomma** [comment]
@ryanhofdotgov For our PostreSQL servers, there are log categories for "QueryStoreRuntimeStatistics" and "QueryStoreWaitStatistics". These appear to be logs for [evaluating performance](https://docs.microsoft.com/en-us/azure/postgresql/concepts-query-store).

Am I correct to assume those categories do _not_ need to be streamed for this specific user story?

**Comment by ryanhofdotgov** [comment]
@kingcomma We can skip those categories for now. They aren't required.

**Comment by kingcomma** [comment]
Split remaining work into #969 and #970.

**Comment by ryanhofdotgov** [comment]
Important reference when Splunk access is handled by an app registration:
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-application
App registration needs Azure Event Hubs Data Receiver role on the instance (e.g., /logs)
