### ISSUE TITLE
Stream resource logs to an event hub

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#969]
Resource logs to stream:

- [ ] Per-state ETL Functions (#1017)
- [x] Participant records PostgreSQL Server (#975)
- [x] Core PostgreSQL Server (#975)
- [x] Query Tool and Dashboard App Service instances (#962)
- [x] Metrics API and Collection Functions (#1015)
